export const INDIAN_STATES = [
  "Bihar",
  "Delhi",
  "Uttar Pradesh",
  "Jharkhand",
  "West Bengal",
  "Maharashtra",
  "Karnataka",
  "Tamil Nadu",
  "Telangana",
  "Gujarat",
  "Rajasthan",
  "Madhya Pradesh",
  "Punjab",
  "Haryana",
  "Odisha",
  "Kerala",
  "Assam",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Chhattisgarh",
  "Goa",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Ladakh",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Sikkim",
  "Tripura",
  "Uttarakhand",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Lakshadweep",
  "Puducherry",
];

export const BIHAR_DISTRICTS = [
  "Darbhanga",
  "Madhubani",
  "Samastipur",
  "Muzaffarpur",
  "Patna",
  "Gaya",
  "Bhagalpur",
  "Purnia",
  "Sitamarhi",
  "Vaishali",
  "Begusarai",
  "Nalanda",
  "Siwan",
  "Saran",
  "East Champaran",
  "West Champaran",
  "Rohtas",
  "Katihar",
  "Saharsa",
  "Munger",
  "Araria",
  "Kishanganj",
  "Bhojpur",
  "Buxar",
  "Banka",
  "Jamui",
  "Jehanabad",
  "Khagaria",
  "Lakhisarai",
  "Madhepura",
  "Nawada",
  "Sheikhpura",
  "Sheohar",
  "Supaul",
  "Gopalganj",
  "Kaimur",
  "Arwal",
  "Aurangabad",
];

export const DELHI_DISTRICTS = [
  "Central Delhi",
  "East Delhi",
  "New Delhi",
  "North Delhi",
  "North East Delhi",
  "North West Delhi",
  "Shahdara",
  "South Delhi",
  "South East Delhi",
  "South West Delhi",
  "West Delhi",
];
