/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsWomenEmpowermentRouteImport } from './routes/programs/women-empowerment'
import { Route as ProgramsSkillsDevelopmentRouteImport } from './routes/programs/skills-development'
import { Route as ProgramsEducationRouteImport } from './routes/programs/education'
import { Route as AboutVision2047RouteImport } from './routes/about_/vision-2047'
import { Route as AboutObjectiveAndVisionRouteImport } from './routes/about_/objective-and-vision'
import { Route as ProgramsHealthcareIndexRouteImport } from './routes/programs/healthcare/index'
import { Route as ProgramsHealthcareWellnessCentresRouteImport } from './routes/programs/healthcare/wellness-centres'
import { Route as ProgramsHealthcareRuralAmbulanceRouteImport } from './routes/programs/healthcare/rural-ambulance'
import { Route as ProgramsHealthcareMenstrualHygieneRouteImport } from './routes/programs/healthcare/menstrual-hygiene'
import { Route as ProgramsHealthcareMedicalAidRouteImport } from './routes/programs/healthcare/medical-aid'
import { Route as ProgramsHealthcareHealthCheckupCampsRouteImport } from './routes/programs/healthcare/health-checkup-camps'
import { Route as ProgramsHealthcareDiabetesPreventionRouteImport } from './routes/programs/healthcare/diabetes-prevention'
import { Route as ProgramsHealthcareCriticalLifeSupportRouteImport } from './routes/programs/healthcare/critical-life-support'
import { Route as ProgramsHealthcareCervicalCancerRouteImport } from './routes/programs/healthcare/cervical-cancer'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsWomenEmpowermentRoute =
  ProgramsWomenEmpowermentRouteImport.update({
    id: '/programs/women-empowerment',
    path: '/programs/women-empowerment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsSkillsDevelopmentRoute =
  ProgramsSkillsDevelopmentRouteImport.update({
    id: '/programs/skills-development',
    path: '/programs/skills-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsEducationRoute = ProgramsEducationRouteImport.update({
  id: '/programs/education',
  path: '/programs/education',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutVision2047Route = AboutVision2047RouteImport.update({
  id: '/about_/vision-2047',
  path: '/about/vision-2047',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutObjectiveAndVisionRoute = AboutObjectiveAndVisionRouteImport.update({
  id: '/about_/objective-and-vision',
  path: '/about/objective-and-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsHealthcareIndexRoute = ProgramsHealthcareIndexRouteImport.update({
  id: '/programs/healthcare/',
  path: '/programs/healthcare/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsHealthcareWellnessCentresRoute =
  ProgramsHealthcareWellnessCentresRouteImport.update({
    id: '/programs/healthcare/wellness-centres',
    path: '/programs/healthcare/wellness-centres',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsHealthcareRuralAmbulanceRoute =
  ProgramsHealthcareRuralAmbulanceRouteImport.update({
    id: '/programs/healthcare/rural-ambulance',
    path: '/programs/healthcare/rural-ambulance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsHealthcareMenstrualHygieneRoute =
  ProgramsHealthcareMenstrualHygieneRouteImport.update({
    id: '/programs/healthcare/menstrual-hygiene',
    path: '/programs/healthcare/menstrual-hygiene',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsHealthcareMedicalAidRoute =
  ProgramsHealthcareMedicalAidRouteImport.update({
    id: '/programs/healthcare/medical-aid',
    path: '/programs/healthcare/medical-aid',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsHealthcareHealthCheckupCampsRoute =
  ProgramsHealthcareHealthCheckupCampsRouteImport.update({
    id: '/programs/healthcare/health-checkup-camps',
    path: '/programs/healthcare/health-checkup-camps',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsHealthcareDiabetesPreventionRoute =
  ProgramsHealthcareDiabetesPreventionRouteImport.update({
    id: '/programs/healthcare/diabetes-prevention',
    path: '/programs/healthcare/diabetes-prevention',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsHealthcareCriticalLifeSupportRoute =
  ProgramsHealthcareCriticalLifeSupportRouteImport.update({
    id: '/programs/healthcare/critical-life-support',
    path: '/programs/healthcare/critical-life-support',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsHealthcareCervicalCancerRoute =
  ProgramsHealthcareCervicalCancerRouteImport.update({
    id: '/programs/healthcare/cervical-cancer',
    path: '/programs/healthcare/cervical-cancer',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/about/objective-and-vision': typeof AboutObjectiveAndVisionRoute
  '/about/vision-2047': typeof AboutVision2047Route
  '/programs/education': typeof ProgramsEducationRoute
  '/programs/skills-development': typeof ProgramsSkillsDevelopmentRoute
  '/programs/women-empowerment': typeof ProgramsWomenEmpowermentRoute
  '/programs/healthcare/cervical-cancer': typeof ProgramsHealthcareCervicalCancerRoute
  '/programs/healthcare/critical-life-support': typeof ProgramsHealthcareCriticalLifeSupportRoute
  '/programs/healthcare/diabetes-prevention': typeof ProgramsHealthcareDiabetesPreventionRoute
  '/programs/healthcare/health-checkup-camps': typeof ProgramsHealthcareHealthCheckupCampsRoute
  '/programs/healthcare/medical-aid': typeof ProgramsHealthcareMedicalAidRoute
  '/programs/healthcare/menstrual-hygiene': typeof ProgramsHealthcareMenstrualHygieneRoute
  '/programs/healthcare/rural-ambulance': typeof ProgramsHealthcareRuralAmbulanceRoute
  '/programs/healthcare/wellness-centres': typeof ProgramsHealthcareWellnessCentresRoute
  '/programs/healthcare/': typeof ProgramsHealthcareIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/about/objective-and-vision': typeof AboutObjectiveAndVisionRoute
  '/about/vision-2047': typeof AboutVision2047Route
  '/programs/education': typeof ProgramsEducationRoute
  '/programs/skills-development': typeof ProgramsSkillsDevelopmentRoute
  '/programs/women-empowerment': typeof ProgramsWomenEmpowermentRoute
  '/programs/healthcare/cervical-cancer': typeof ProgramsHealthcareCervicalCancerRoute
  '/programs/healthcare/critical-life-support': typeof ProgramsHealthcareCriticalLifeSupportRoute
  '/programs/healthcare/diabetes-prevention': typeof ProgramsHealthcareDiabetesPreventionRoute
  '/programs/healthcare/health-checkup-camps': typeof ProgramsHealthcareHealthCheckupCampsRoute
  '/programs/healthcare/medical-aid': typeof ProgramsHealthcareMedicalAidRoute
  '/programs/healthcare/menstrual-hygiene': typeof ProgramsHealthcareMenstrualHygieneRoute
  '/programs/healthcare/rural-ambulance': typeof ProgramsHealthcareRuralAmbulanceRoute
  '/programs/healthcare/wellness-centres': typeof ProgramsHealthcareWellnessCentresRoute
  '/programs/healthcare': typeof ProgramsHealthcareIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/about_/objective-and-vision': typeof AboutObjectiveAndVisionRoute
  '/about_/vision-2047': typeof AboutVision2047Route
  '/programs/education': typeof ProgramsEducationRoute
  '/programs/skills-development': typeof ProgramsSkillsDevelopmentRoute
  '/programs/women-empowerment': typeof ProgramsWomenEmpowermentRoute
  '/programs/healthcare/cervical-cancer': typeof ProgramsHealthcareCervicalCancerRoute
  '/programs/healthcare/critical-life-support': typeof ProgramsHealthcareCriticalLifeSupportRoute
  '/programs/healthcare/diabetes-prevention': typeof ProgramsHealthcareDiabetesPreventionRoute
  '/programs/healthcare/health-checkup-camps': typeof ProgramsHealthcareHealthCheckupCampsRoute
  '/programs/healthcare/medical-aid': typeof ProgramsHealthcareMedicalAidRoute
  '/programs/healthcare/menstrual-hygiene': typeof ProgramsHealthcareMenstrualHygieneRoute
  '/programs/healthcare/rural-ambulance': typeof ProgramsHealthcareRuralAmbulanceRoute
  '/programs/healthcare/wellness-centres': typeof ProgramsHealthcareWellnessCentresRoute
  '/programs/healthcare/': typeof ProgramsHealthcareIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
    | '/about/objective-and-vision'
    | '/about/vision-2047'
    | '/programs/education'
    | '/programs/skills-development'
    | '/programs/women-empowerment'
    | '/programs/healthcare/cervical-cancer'
    | '/programs/healthcare/critical-life-support'
    | '/programs/healthcare/diabetes-prevention'
    | '/programs/healthcare/health-checkup-camps'
    | '/programs/healthcare/medical-aid'
    | '/programs/healthcare/menstrual-hygiene'
    | '/programs/healthcare/rural-ambulance'
    | '/programs/healthcare/wellness-centres'
    | '/programs/healthcare/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
    | '/about/objective-and-vision'
    | '/about/vision-2047'
    | '/programs/education'
    | '/programs/skills-development'
    | '/programs/women-empowerment'
    | '/programs/healthcare/cervical-cancer'
    | '/programs/healthcare/critical-life-support'
    | '/programs/healthcare/diabetes-prevention'
    | '/programs/healthcare/health-checkup-camps'
    | '/programs/healthcare/medical-aid'
    | '/programs/healthcare/menstrual-hygiene'
    | '/programs/healthcare/rural-ambulance'
    | '/programs/healthcare/wellness-centres'
    | '/programs/healthcare'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
    | '/about_/objective-and-vision'
    | '/about_/vision-2047'
    | '/programs/education'
    | '/programs/skills-development'
    | '/programs/women-empowerment'
    | '/programs/healthcare/cervical-cancer'
    | '/programs/healthcare/critical-life-support'
    | '/programs/healthcare/diabetes-prevention'
    | '/programs/healthcare/health-checkup-camps'
    | '/programs/healthcare/medical-aid'
    | '/programs/healthcare/menstrual-hygiene'
    | '/programs/healthcare/rural-ambulance'
    | '/programs/healthcare/wellness-centres'
    | '/programs/healthcare/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  AboutObjectiveAndVisionRoute: typeof AboutObjectiveAndVisionRoute
  AboutVision2047Route: typeof AboutVision2047Route
  ProgramsEducationRoute: typeof ProgramsEducationRoute
  ProgramsSkillsDevelopmentRoute: typeof ProgramsSkillsDevelopmentRoute
  ProgramsWomenEmpowermentRoute: typeof ProgramsWomenEmpowermentRoute
  ProgramsHealthcareCervicalCancerRoute: typeof ProgramsHealthcareCervicalCancerRoute
  ProgramsHealthcareCriticalLifeSupportRoute: typeof ProgramsHealthcareCriticalLifeSupportRoute
  ProgramsHealthcareDiabetesPreventionRoute: typeof ProgramsHealthcareDiabetesPreventionRoute
  ProgramsHealthcareHealthCheckupCampsRoute: typeof ProgramsHealthcareHealthCheckupCampsRoute
  ProgramsHealthcareMedicalAidRoute: typeof ProgramsHealthcareMedicalAidRoute
  ProgramsHealthcareMenstrualHygieneRoute: typeof ProgramsHealthcareMenstrualHygieneRoute
  ProgramsHealthcareRuralAmbulanceRoute: typeof ProgramsHealthcareRuralAmbulanceRoute
  ProgramsHealthcareWellnessCentresRoute: typeof ProgramsHealthcareWellnessCentresRoute
  ProgramsHealthcareIndexRoute: typeof ProgramsHealthcareIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/women-empowerment': {
      id: '/programs/women-empowerment'
      path: '/programs/women-empowerment'
      fullPath: '/programs/women-empowerment'
      preLoaderRoute: typeof ProgramsWomenEmpowermentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/skills-development': {
      id: '/programs/skills-development'
      path: '/programs/skills-development'
      fullPath: '/programs/skills-development'
      preLoaderRoute: typeof ProgramsSkillsDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/education': {
      id: '/programs/education'
      path: '/programs/education'
      fullPath: '/programs/education'
      preLoaderRoute: typeof ProgramsEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/vision-2047': {
      id: '/about_/vision-2047'
      path: '/about/vision-2047'
      fullPath: '/about/vision-2047'
      preLoaderRoute: typeof AboutVision2047RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/objective-and-vision': {
      id: '/about_/objective-and-vision'
      path: '/about/objective-and-vision'
      fullPath: '/about/objective-and-vision'
      preLoaderRoute: typeof AboutObjectiveAndVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/healthcare/': {
      id: '/programs/healthcare/'
      path: '/programs/healthcare'
      fullPath: '/programs/healthcare/'
      preLoaderRoute: typeof ProgramsHealthcareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/healthcare/wellness-centres': {
      id: '/programs/healthcare/wellness-centres'
      path: '/programs/healthcare/wellness-centres'
      fullPath: '/programs/healthcare/wellness-centres'
      preLoaderRoute: typeof ProgramsHealthcareWellnessCentresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/healthcare/rural-ambulance': {
      id: '/programs/healthcare/rural-ambulance'
      path: '/programs/healthcare/rural-ambulance'
      fullPath: '/programs/healthcare/rural-ambulance'
      preLoaderRoute: typeof ProgramsHealthcareRuralAmbulanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/healthcare/menstrual-hygiene': {
      id: '/programs/healthcare/menstrual-hygiene'
      path: '/programs/healthcare/menstrual-hygiene'
      fullPath: '/programs/healthcare/menstrual-hygiene'
      preLoaderRoute: typeof ProgramsHealthcareMenstrualHygieneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/healthcare/medical-aid': {
      id: '/programs/healthcare/medical-aid'
      path: '/programs/healthcare/medical-aid'
      fullPath: '/programs/healthcare/medical-aid'
      preLoaderRoute: typeof ProgramsHealthcareMedicalAidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/healthcare/health-checkup-camps': {
      id: '/programs/healthcare/health-checkup-camps'
      path: '/programs/healthcare/health-checkup-camps'
      fullPath: '/programs/healthcare/health-checkup-camps'
      preLoaderRoute: typeof ProgramsHealthcareHealthCheckupCampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/healthcare/diabetes-prevention': {
      id: '/programs/healthcare/diabetes-prevention'
      path: '/programs/healthcare/diabetes-prevention'
      fullPath: '/programs/healthcare/diabetes-prevention'
      preLoaderRoute: typeof ProgramsHealthcareDiabetesPreventionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/healthcare/critical-life-support': {
      id: '/programs/healthcare/critical-life-support'
      path: '/programs/healthcare/critical-life-support'
      fullPath: '/programs/healthcare/critical-life-support'
      preLoaderRoute: typeof ProgramsHealthcareCriticalLifeSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/healthcare/cervical-cancer': {
      id: '/programs/healthcare/cervical-cancer'
      path: '/programs/healthcare/cervical-cancer'
      fullPath: '/programs/healthcare/cervical-cancer'
      preLoaderRoute: typeof ProgramsHealthcareCervicalCancerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  AboutObjectiveAndVisionRoute: AboutObjectiveAndVisionRoute,
  AboutVision2047Route: AboutVision2047Route,
  ProgramsEducationRoute: ProgramsEducationRoute,
  ProgramsSkillsDevelopmentRoute: ProgramsSkillsDevelopmentRoute,
  ProgramsWomenEmpowermentRoute: ProgramsWomenEmpowermentRoute,
  ProgramsHealthcareCervicalCancerRoute: ProgramsHealthcareCervicalCancerRoute,
  ProgramsHealthcareCriticalLifeSupportRoute:
    ProgramsHealthcareCriticalLifeSupportRoute,
  ProgramsHealthcareDiabetesPreventionRoute:
    ProgramsHealthcareDiabetesPreventionRoute,
  ProgramsHealthcareHealthCheckupCampsRoute:
    ProgramsHealthcareHealthCheckupCampsRoute,
  ProgramsHealthcareMedicalAidRoute: ProgramsHealthcareMedicalAidRoute,
  ProgramsHealthcareMenstrualHygieneRoute:
    ProgramsHealthcareMenstrualHygieneRoute,
  ProgramsHealthcareRuralAmbulanceRoute: ProgramsHealthcareRuralAmbulanceRoute,
  ProgramsHealthcareWellnessCentresRoute:
    ProgramsHealthcareWellnessCentresRoute,
  ProgramsHealthcareIndexRoute: ProgramsHealthcareIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
